// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY8cmlu0uWYEVy_qFhbgTzB6C5pMmdQWI',
    appId: '1:360744678302:web:5e19e7db4fd7b4dfeb1c8f',
    messagingSenderId: '360744678302',
    projectId: 'fir-project-auth-2857f',
    authDomain: 'fir-project-auth-2857f.firebaseapp.com',
    storageBucket: 'fir-project-auth-2857f.appspot.com',
    measurementId: 'G-1ZF30WF1FQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbiNTmqOWs32frqOHasTvhjRmDFN_IGrM',
    appId: '1:360744678302:android:00e85a4584b952d1eb1c8f',
    messagingSenderId: '360744678302',
    projectId: 'fir-project-auth-2857f',
    storageBucket: 'fir-project-auth-2857f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-jmVWTQZC6wlOyQX6CyqrpbbECjTJpVg',
    appId: '1:360744678302:ios:b50dd56f4a8d3c30eb1c8f',
    messagingSenderId: '360744678302',
    projectId: 'fir-project-auth-2857f',
    storageBucket: 'fir-project-auth-2857f.appspot.com',
    androidClientId: '360744678302-s4l37d1u4ns8d4g51sm468vv5h65l6hv.apps.googleusercontent.com',
    iosClientId: '360744678302-qfudesiojg3oj0b1sibh6n4j0dapvpeg.apps.googleusercontent.com',
    iosBundleId: 'com.example.oyoClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-jmVWTQZC6wlOyQX6CyqrpbbECjTJpVg',
    appId: '1:360744678302:ios:b50dd56f4a8d3c30eb1c8f',
    messagingSenderId: '360744678302',
    projectId: 'fir-project-auth-2857f',
    storageBucket: 'fir-project-auth-2857f.appspot.com',
    androidClientId: '360744678302-s4l37d1u4ns8d4g51sm468vv5h65l6hv.apps.googleusercontent.com',
    iosClientId: '360744678302-qfudesiojg3oj0b1sibh6n4j0dapvpeg.apps.googleusercontent.com',
    iosBundleId: 'com.example.oyoClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY8cmlu0uWYEVy_qFhbgTzB6C5pMmdQWI',
    appId: '1:360744678302:web:60ca15f94c8c68a3eb1c8f',
    messagingSenderId: '360744678302',
    projectId: 'fir-project-auth-2857f',
    authDomain: 'fir-project-auth-2857f.firebaseapp.com',
    storageBucket: 'fir-project-auth-2857f.appspot.com',
    measurementId: 'G-1RJKLSVJGQ',
  );
}
