import 'package:flutter/material.dart';

List imageList = [
  {
    'img1' : 'asset/hotelImage/hotel1/1.webp',
    'img2' : 'asset/hotelImage/hotel1/2.webp',
    'img3' : 'asset/hotelImage/hotel1/3.webp',
    'img4' : 'asset/hotelImage/hotel1/4.webp',
    'img5' : 'asset/hotelImage/hotel1/5.webp',
    'img6' : 'asset/hotelImage/hotel1/6.jpeg',
  },
  {
    'img1' : 'asset/hotelImage/hotel2/1.jpg',
    'img2' : 'asset/hotelImage/hotel2/2.jpeg',
    'img3' : 'asset/hotelImage/hotel2/3.jpeg',
    'img4' : 'asset/hotelImage/hotel2/4.jpeg',
    'img5' : 'asset/hotelImage/hotel2/5.jpeg',
    'img6' : 'asset/hotelImage/hotel2/6.jpeg',
    'img7' : 'asset/hotelImage/hotel2/7.jpeg',
  },
  {
    'img1' : 'asset/hotelImage/hotel3/1.jpg',
    'img2' : 'asset/hotelImage/hotel3/2.jpeg',
    'img3' : 'asset/hotelImage/hotel3/3.jpeg',
    'img4' : 'asset/hotelImage/hotel3/4.jpeg',
    'img5' : 'asset/hotelImage/hotel3/5.jpeg',
    'img6' : 'asset/hotelImage/hotel3/6.jpeg',
  },
  {
    'img1' : 'asset/hotelImage/hotel4/1.jpeg',
    'img2' : 'asset/hotelImage/hotel4/2.jpeg',
    'img3' : 'asset/hotelImage/hotel4/3.jpeg',
    'img4' : 'asset/hotelImage/hotel4/4.jpeg',
    'img5' : 'asset/hotelImage/hotel4/5.jpg',
    'img6' : 'asset/hotelImage/hotel4/6.webp',
  },
  {
    'img1' : 'asset/hotelImage/hotel5/1.webp',
    'img2' : 'asset/hotelImage/hotel5/2.jpeg',
    'img3' : 'asset/hotelImage/hotel5/3.jpeg',
    'img4' : 'asset/hotelImage/hotel5/4.jpeg',
    'img5' : 'asset/hotelImage/hotel5/5.webp',
    'img6' : 'asset/hotelImage/hotel5/6.jpeg',
  },
  {
    'img1' : 'asset/hotelImage/hotel6/1.jpeg',
    'img2' : 'asset/hotelImage/hotel6/2.jpeg',
    'img3' : 'asset/hotelImage/hotel6/3.jpeg',
    'img4' : 'asset/hotelImage/hotel6/4.jpeg',
    'img5' : 'asset/hotelImage/hotel6/5.jpeg',
    'img6' : 'asset/hotelImage/hotel6/6.webp',
  },
  {
    'img1' : 'asset/hotelImage/hotel7/1.jpeg',
    'img2' : 'asset/hotelImage/hotel7/2.jpeg',
    'img3' : 'asset/hotelImage/hotel7/3.jpg',
    'img4' : 'asset/hotelImage/hotel7/4.jpeg',
    'img5' : 'asset/hotelImage/hotel7/5.jpeg',
    'img6' : 'asset/hotelImage/hotel7/6.jpeg',
  },
  {
    'img1' : 'asset/hotelImage/hotel8/1.webp',
    'img2' : 'asset/hotelImage/hotel8/2.jpeg',
    'img3' : 'asset/hotelImage/hotel8/3.jpeg',
    'img4' : 'asset/hotelImage/hotel8/4.jpeg',
    'img5' : 'asset/hotelImage/hotel8/5.jpeg',
    'img6' : 'asset/hotelImage/hotel8/6.jpeg',
  },
  {
    'img1' : 'asset/hotelImage/hotel9/1.jpeg',
    'img2' : 'asset/hotelImage/hotel9/2.jpeg',
    'img3' : 'asset/hotelImage/hotel9/3.jpeg',
    'img4' : 'asset/hotelImage/hotel9/4.jpeg',
    'img5' : 'asset/hotelImage/hotel9/5.jpeg',
    'img6' : 'asset/hotelImage/hotel9/6.jpeg',
  },
  {
    'img1' : 'asset/hotelImage/hotel10/1.jpeg',
    'img2' : 'asset/hotelImage/hotel10/2.png',
    'img3' : 'asset/hotelImage/hotel10/3.png',
    'img4' : 'asset/hotelImage/hotel10/4.png',
    'img5' : 'asset/hotelImage/hotel10/5.png',
    'img6' : 'asset/hotelImage/hotel10/6.png',
  },
  {
    'img1' : 'asset/hotelImage/hotel11/1.jpg',
    'img2' : 'asset/hotelImage/hotel11/2.jpeg',
    'img3' : 'asset/hotelImage/hotel11/3.jpeg',
    'img4' : 'asset/hotelImage/hotel11/4.jpeg',
    'img5' : 'asset/hotelImage/hotel11/5.jpeg',
    'img6' : 'asset/hotelImage/hotel11/6.jpeg',
  },
  {
    'img1' : 'asset/hotelImage/hotel12/1.jpeg',
    'img2' : 'asset/hotelImage/hotel12/2.webp',
    'img3' : 'asset/hotelImage/hotel12/3.jpeg',
    'img4' : 'asset/hotelImage/hotel12/4.jpeg',
    'img5' : 'asset/hotelImage/hotel12/5.jpeg',
    'img6' : 'asset/hotelImage/hotel12/6.jpeg',
  },
  {
    'img1' : 'asset/hotelImage/hotel13/1.jpeg',
    'img2' : 'asset/hotelImage/hotel13/2.webp',
    'img3' : 'asset/hotelImage/hotel13/3.jpeg',
    'img4' : 'asset/hotelImage/hotel13/4.jpeg',
    'img5' : 'asset/hotelImage/hotel13/5.jpeg',
    'img6' : 'asset/hotelImage/hotel13/6.jpeg',
  },
  {
    'img1' : 'asset/hotelImage/hotel14/1.jpeg',
    'img2' : 'asset/hotelImage/hotel14/2.jpeg',
    'img3' : 'asset/hotelImage/hotel14/3.jpeg',
    'img4' : 'asset/hotelImage/hotel14/4.jpeg',
    'img5' : 'asset/hotelImage/hotel14/5.jpeg',
    'img6' : 'asset/hotelImage/hotel14/6.jpeg',
  },
  {
    'img1' : 'asset/hotelImage/hotel15/1.jpeg',
    'img2' : 'asset/hotelImage/hotel15/2.jpg',
    'img3' : 'asset/hotelImage/hotel15/3.jpeg',
    'img4' : 'asset/hotelImage/hotel15/4.jpeg',
    'img5' : 'asset/hotelImage/hotel15/5.jpeg',
    'img6' : 'asset/hotelImage/hotel15/6.jpeg',
  },
  {
    'img1' : 'asset/hotelImage/hotel16/1.jpeg',
    'img2' : 'asset/hotelImage/hotel16/2.jpeg',
    'img3' : 'asset/hotelImage/hotel16/3.jpeg',
    'img4' : 'asset/hotelImage/hotel16/4.jpeg',
    'img5' : 'asset/hotelImage/hotel16/5.jpeg',
    'img6' : 'asset/hotelImage/hotel16/6.jpeg',
  },
  {
    'img1' : 'asset/hotelImage/hotel17/1.jpeg',
    'img2' : 'asset/hotelImage/hotel17/2.jpeg',
    'img3' : 'asset/hotelImage/hotel17/3.jpeg',
    'img4' : 'asset/hotelImage/hotel17/4.jpeg',
    'img5' : 'asset/hotelImage/hotel17/5.jpeg',
  },
  {
    'img1' : 'asset/hotelImage/hotel18/1.webp',
    'img2' : 'asset/hotelImage/hotel18/2.jpeg',
    'img3' : 'asset/hotelImage/hotel18/3.jpeg',
    'img4' : 'asset/hotelImage/hotel18/4.jpeg',
    'img5' : 'asset/hotelImage/hotel18/5.jpeg',
    'img6' : 'asset/hotelImage/hotel18/6.jpeg',
  },
  {
    'img1' : 'asset/hotelImage/hotel19/1.jpg',
    'img2' : 'asset/hotelImage/hotel19/2.jpeg',
    'img3' : 'asset/hotelImage/hotel19/3.jpeg',
    'img4' : 'asset/hotelImage/hotel19/4.jpeg',
    'img5' : 'asset/hotelImage/hotel19/5.jpeg',
    'img6' : 'asset/hotelImage/hotel19/6.jpeg',
  },
  {
    'img1' : 'asset/hotelImage/hotel20/1.jpg',
    'img2' : 'asset/hotelImage/hotel20/2.jpeg',
    'img3' : 'asset/hotelImage/hotel20/3.jpeg',
    'img4' : 'asset/hotelImage/hotel20/4.jpeg',
    'img5' : 'asset/hotelImage/hotel20/5.jpeg',
    'img6' : 'asset/hotelImage/hotel20/6.jpeg',
    'img7' : 'asset/hotelImage/hotel20/7.jpeg',
    'img8' : 'asset/hotelImage/hotel20/8.jpeg',
    'img9' : 'asset/hotelImage/hotel20/9.jpeg',
    'img10' : 'asset/hotelImage/hotel20/10.jpeg',
    'img11' : 'asset/hotelImage/hotel20/11.jpeg',
  },
];